name: Release & Deploy (Frontend)

on:
  release:
    types: [published] # Triggered when a GitHub Release is published

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # Specify the environment for deployment
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }} # Checkout the specific tag

      - name: Setup Fly.io CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          ~/.fly/bin/flyctl deploy --remote-only
